// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfTVZCvnRP1YA7wlmVvAWxrBnRJ5mpmbs',
    appId: '1:439469744343:web:1c002bb98ccd2791271092',
    messagingSenderId: '439469744343',
    projectId: 'docmind-37d17',
    authDomain: 'docmind-37d17.firebaseapp.com',
    storageBucket: 'docmind-37d17.firebasestorage.app',
    measurementId: 'G-0W81T5RMBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOyiUERbKtO72BJOJBx0UH-Oc94iWvRXI',
    appId: '1:439469744343:android:9935eace8f5af95c271092',
    messagingSenderId: '439469744343',
    projectId: 'docmind-37d17',
    storageBucket: 'docmind-37d17.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwGyCdp7nD-Z-WUyuMdU-C5uVHlWCXx8',
    appId: '1:439469744343:ios:98f1dfa8f61c685a271092',
    messagingSenderId: '439469744343',
    projectId: 'docmind-37d17',
    storageBucket: 'docmind-37d17.firebasestorage.app',
    iosBundleId: 'com.example.documentLens',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjwGyCdp7nD-Z-WUyuMdU-C5uVHlWCXx8',
    appId: '1:439469744343:ios:98f1dfa8f61c685a271092',
    messagingSenderId: '439469744343',
    projectId: 'docmind-37d17',
    storageBucket: 'docmind-37d17.firebasestorage.app',
    iosBundleId: 'com.example.documentLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfTVZCvnRP1YA7wlmVvAWxrBnRJ5mpmbs',
    appId: '1:439469744343:web:041f84987b8be7f7271092',
    messagingSenderId: '439469744343',
    projectId: 'docmind-37d17',
    authDomain: 'docmind-37d17.firebaseapp.com',
    storageBucket: 'docmind-37d17.firebasestorage.app',
    measurementId: 'G-XTD0B1JR78',
  );
}
